[gRPC]
port = 1628

[Logging]
level = "DEBUG"

[Token]
algorithm = "HS256"
secret = "secret"
accessTokenDuringLife = 15
refreshTokenDuringLife = 30

[AuthFromVK]
getAccessTokenBaseURL = "https://oauth.vk.com/access_token"
clientID = "51617193"
clientSecret = "secret"
redirectURI = "http://127.0.0.1:6543/verifyVK"
